MODEL:
  TYPE: vit
  NAME: simmim_finetune
  DROP_PATH_RATE: 0.06
  VIT:
    PATCH_SIZE: 4
    EMBED_DIM: 384
    DEPTH: 4
    NUM_HEADS: 12
    USE_APE: False
    USE_RPB: True
    USE_SHARED_RPB: False
    USE_MEAN_POOLING: False
DATA:
  IMG_SIZE: 32
TRAIN:
  EPOCHS: 100
  WARMUP_EPOCHS: 7
  BASE_LR: 5e-3
  WARMUP_LR: 5.25e-5
  MIN_LR: 5e-6
  WEIGHT_DECAY: 0.05
  LAYER_DECAY: 0.825
PRINT_FREQ: 100
SAVE_FREQ: 5
TAG: simmim_finetune__vit_d4__cifar10__100ep
